# Configuración para que funcione tanto en Local como en Railway automáticamente
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:donantes}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.servlet.context-path=/api
# Configuración de Hibernate/JPA para que cree las tablas solas al subir
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true